verbosity                = 2
default_tasks            = ["locs::report"]
action_string_formatting = "new"

[tool.doot]

[tool.doot.notify]
say-on-exit = false

[tool.doot.globbing]
ignores = ['.git', '.DS_Store', "__pycache__"]

[tool.doot.globbing]
ignores  = ['.git', '.DS_Store', "__pycache__"]

[tool.doot.subtask]
sleep = 1

[tool.doot.batch]
sleep   = 5

[tool.doot.directories]
src     = "bkmkorg"
build   = "build"

[tool.doot.group.pip]
