verbosity                = 2
default_tasks            = ["locs::report"]
action_string_formatting = "new"

[tool.doot]
say-on-exit = false
glob_ignores = ['.git', '.DS_Store', "__pycache__"]

[tool.doot.directories]
src     = "bkmkorg"
build   = "build"
