verbosity                = 2
default_tasks            = ["locs::report"]
action_string_formatting = "new"

[notify]
say-on-exit = false

[globbing]
ignores = ['.git', '.DS_Store', "__pycache__"]

[globbing]
ignores  = ['.git', '.DS_Store', "__pycache__"]

[subtask]
sleep = 1

[batch]
sleep   = 5

[directories]
src     = "bkmkorg"
build   = "build"

[group.pip]
