[DEFAULT]
MAX_ATTEMPTS  = 20
tweet_len     = 280
toot_len      = 480
twitter_sleep = true
secrets_loc   = "secrets.toml"

[PHOTO]
WHITE_LIST           = "dcim_whitelist"
TEMP_LOC             = "/Volumes/documents/DCIM/__temp/output.jpg"
convert_args         = ["-define", "jpeg:extent=4800KB"]
resolution_blacklist = "resolution_blacklist"

[BIBTEX]
lib         = "~/github/writing/resources/bibliography"
success_log = "bibtex_post.log"
fail_log    = "rejected_tweets.log"
blacklist   = "bibtex_blacklist"
stub_source = "/Volumes/documents/in_progress_pdfs/Current/"
stub_target = "~/github/writing/resources/todo.bib"
stub_exts   = [".pdf", ".epub"]

[BIBTEX_KEYS]
required = ["year", "author", "title", "tags"]
one_of   = ["doi", "url", "isbn"]

[TIME]
# Double % to handle interpolation
format = "%I:%M %p"
cmd    = "say -v Moira -r 50 \"The Time is {}\""


[BOOKMARK]
firefox  = "~/Library/ApplicationSupport/Firefox"
profiles = "profiles.ini"
database = "places.sqlite"
